### ISSUE TITLE
uri4uri.net unavailable

### ISSUE THREAD

**Issue by IS4Code** [cgutteridge/uri4uri#3]
Hello, it seems uri4uri.net is not available and instead links to some garbage site. According to DNS records, this happened 3 months ago. I even tried to map the domain to its original IP address in `/etc/hosts`, but the web isn't there.

According to the University of Southampton, the site should have been keep online indefinitely. I need its vocabulary and resolution mechanisms for the work I am doing.

**Comment by cgutteridge** [comment]
Hi, this is a hobby site -- in fact it was an April 1st joke about 9 years ago. I decided to stop paying for the DNS entry.  Apologies for breaking the web. Cool URIs don't change but there's no such thing as a cool URI when DNS and hosting isn't free. Eventually all URIs will break.

However you could maybe set up a local copy and use that for your work? All it needs is a generic copy of apache. It uses PHP and a .htaccess file. Then just edit the index.php with your URL and local path.

I still work for university of Southampton but I've lost all funding for working on anything to do with RDF and open data (it stopped being fashionable) so I've drifted away from the topic.

**Comment by IS4Code** [comment]
Thank you for the quick response! Sorry to hear this, but I understand the reasons.

I managed to launch the site (with some additional Apache directives) at https://uri4uri.is4.site/. I am willing to maintain and run the site for now ("indefinitely" as well), if I have your permission. If you could, I would also be glad if you changed the README to point to my site, so it doesn't point to Asian porn or whatever that domain has now become.

I have also moved its vocabulary to PURL in the form of http://purl.org/uri4uri/ so something like this doesn't happen anymore.
